use super::cpu::*;

#[derive(PartialEq)]
#[rustfmt::skip]
pub enum LoadByteTarget {
    A, B, C, D, E, H, L, HLI, HLD, HL, BC, DE, A16,
}

#[derive(PartialEq)]
#[rustfmt::skip]
pub enum LoadByteSource {
    A, B, C, D, E, H, L, D8, HL, HLI, HLD, A16, BC, DE,
}

#[rustfmt::skip]
#[derive(PartialEq)]
pub enum LoadWordSource {
    D16, HL, SP, SPr8,
}

#[rustfmt::skip]
pub enum LoadWordTarget {
    BC, DE, HL, SP, A16,
}

#[derive(PartialEq)]
pub enum LoadOtherTarget {
    A, A8, CAddress,
}

#[derive(PartialEq)]
pub enum LoadOtherSource {
    A, A8, CAddress,
}

pub enum StackTarget {
    BC, DE, HL, AF,
}

pub enum LoadType {
    Byte(LoadByteTarget, LoadByteSource),
    Word(LoadWordTarget, LoadWordSource),
    Other(LoadOtherTarget, LoadOtherSource),
}

pub enum Instructions {
    NOP(),
    HALT(),
    LD(LoadType),
    LDH(LoadType),
    INC(IncDecTarget),
    DEC(IncDecTarget),
    ADD(ArithmeticTarget, ArithmeticSource),
    ADD16(Arithmetic16Target),
    SUB(ArithmeticSource),
    JR(JumpTest),
    JP(JumpTest),
    ADC(ArithmeticSource),
    SBC(ArithmeticSource),
    AND(ArithmeticSource),
    XOR(ArithmeticSource),
    OR(ArithmeticSource),
    CP(ArithmeticSource),
    RST(RSTTargets),
    CPL(),
    JPHL(),
    CCF(),
    DI(),
    EI(),
    DAA(),
    SCF(),
    PUSH(StackTarget),
    POP(StackTarget),
    CALL(JumpTest),
    RET(JumpTest),
    RETI(),
    RLCA(),
    RRCA(),
    RRC(ArithmeticSource),
    RLA(),
    RRA(),

    /* CB Instructions */
    RLC(ArithmeticSource),
    RL(ArithmeticSource),
    RR(ArithmeticSource),
    SLA(ArithmeticSource),
    SRA(ArithmeticSource),
    SWAP(ArithmeticSource),
    SRL(ArithmeticSource),
    BIT(u8, ArithmeticSource),
    RES(u8, ArithmeticSource),
    SET(u8, ArithmeticSource),
}

impl Instructions {
    pub fn from_byte(byte: u8, prefixed: bool) -> Option<Instructions> {
        if prefixed {
            Instructions::from_byte_prefixed(byte)
        } else {
            Instructions::from_byte_not_prefixed(byte)
        }
    }

    pub fn from_byte_prefixed(byte: u8) -> Option<Instructions> {
        match byte {
            0x00 => Some(Instructions::RLC(ArithmeticSource::B)),
            0x01 => Some(Instructions::RLC(ArithmeticSource::C)),
            0x02 => Some(Instructions::RLC(ArithmeticSource::D)),
            0x03 => Some(Instructions::RLC(ArithmeticSource::E)),
            0x04 => Some(Instructions::RLC(ArithmeticSource::H)),
            0x05 => Some(Instructions::RLC(ArithmeticSource::L)),
            0x06 => Some(Instructions::RLC(ArithmeticSource::HLAddr)),
            0x07 => Some(Instructions::RLC(ArithmeticSource::A)),
            0x08 => Some(Instructions::RRC(ArithmeticSource::B)),
            0x09 => Some(Instructions::RRC(ArithmeticSource::C)),
            0x0A => Some(Instructions::RRC(ArithmeticSource::D)),
            0x0B => Some(Instructions::RRC(ArithmeticSource::E)),
            0x0C => Some(Instructions::RRC(ArithmeticSource::H)),
            0x0D => Some(Instructions::RRC(ArithmeticSource::L)),
            0x0E => Some(Instructions::RRC(ArithmeticSource::HLAddr)),
            0x0F => Some(Instructions::RRC(ArithmeticSource::A)),
            0x10 => Some(Instructions::RL(ArithmeticSource::B)),
            0x11 => Some(Instructions::RL(ArithmeticSource::C)),
            0x12 => Some(Instructions::RL(ArithmeticSource::D)),
            0x13 => Some(Instructions::RL(ArithmeticSource::E)),
            0x14 => Some(Instructions::RL(ArithmeticSource::H)),
            0x15 => Some(Instructions::RL(ArithmeticSource::L)),
            0x16 => Some(Instructions::RL(ArithmeticSource::HLAddr)),
            0x17 => Some(Instructions::RL(ArithmeticSource::A)),
            0x18 => Some(Instructions::RR(ArithmeticSource::B)),
            0x19 => Some(Instructions::RR(ArithmeticSource::C)),
            0x1A => Some(Instructions::RR(ArithmeticSource::D)),
            0x1B => Some(Instructions::RR(ArithmeticSource::E)),
            0x1C => Some(Instructions::RR(ArithmeticSource::H)),
            0x1D => Some(Instructions::RR(ArithmeticSource::L)),
            0x1E => Some(Instructions::RR(ArithmeticSource::HLAddr)),
            0x1F => Some(Instructions::RR(ArithmeticSource::A)),
            0x20 => Some(Instructions::SLA(ArithmeticSource::B)),
            0x21 => Some(Instructions::SLA(ArithmeticSource::C)),
            0x22 => Some(Instructions::SLA(ArithmeticSource::D)),
            0x23 => Some(Instructions::SLA(ArithmeticSource::E)),
            0x24 => Some(Instructions::SLA(ArithmeticSource::H)),
            0x25 => Some(Instructions::SLA(ArithmeticSource::L)),
            0x26 => Some(Instructions::SLA(ArithmeticSource::HLAddr)),
            0x27 => Some(Instructions::SLA(ArithmeticSource::A)),
            0x28 => Some(Instructions::SRA(ArithmeticSource::B)),
            0x29 => Some(Instructions::SRA(ArithmeticSource::C)),
            0x2A => Some(Instructions::SRA(ArithmeticSource::D)),
            0x2B => Some(Instructions::SRA(ArithmeticSource::E)),
            0x2C => Some(Instructions::SRA(ArithmeticSource::H)),
            0x2D => Some(Instructions::SRA(ArithmeticSource::L)),
            0x2E => Some(Instructions::SRA(ArithmeticSource::HLAddr)),
            0x2F => Some(Instructions::SRA(ArithmeticSource::A)),
            0x30 => Some(Instructions::SWAP(ArithmeticSource::B)),
            0x31 => Some(Instructions::SWAP(ArithmeticSource::C)),
            0x32 => Some(Instructions::SWAP(ArithmeticSource::D)),
            0x33 => Some(Instructions::SWAP(ArithmeticSource::E)),
            0x34 => Some(Instructions::SWAP(ArithmeticSource::H)),
            0x35 => Some(Instructions::SWAP(ArithmeticSource::L)),
            0x36 => Some(Instructions::SWAP(ArithmeticSource::HLAddr)),
            0x37 => Some(Instructions::SWAP(ArithmeticSource::A)),
            0x38 => Some(Instructions::SRL(ArithmeticSource::B)),
            0x39 => Some(Instructions::SRL(ArithmeticSource::C)),
            0x3A => Some(Instructions::SRL(ArithmeticSource::D)),
            0x3B => Some(Instructions::SRL(ArithmeticSource::E)),
            0x3C => Some(Instructions::SRL(ArithmeticSource::H)),
            0x3D => Some(Instructions::SRL(ArithmeticSource::L)),
            0x3E => Some(Instructions::SRL(ArithmeticSource::HLAddr)),
            0x3F => Some(Instructions::SRL(ArithmeticSource::A)),
            0x40 => Some(Instructions::BIT(0, ArithmeticSource::B)),
            0x41 => Some(Instructions::BIT(0, ArithmeticSource::C)),
            0x42 => Some(Instructions::BIT(0, ArithmeticSource::D)),
            0x43 => Some(Instructions::BIT(0, ArithmeticSource::E)),
            0x44 => Some(Instructions::BIT(0, ArithmeticSource::H)),
            0x45 => Some(Instructions::BIT(0, ArithmeticSource::L)),
            0x46 => Some(Instructions::BIT(0, ArithmeticSource::HLAddr)),
            0x47 => Some(Instructions::BIT(0, ArithmeticSource::A)),
            0x48 => Some(Instructions::BIT(1, ArithmeticSource::B)),
            0x49 => Some(Instructions::BIT(1, ArithmeticSource::C)),
            0x4A => Some(Instructions::BIT(1, ArithmeticSource::D)),
            0x4B => Some(Instructions::BIT(1, ArithmeticSource::E)),
            0x4C => Some(Instructions::BIT(1, ArithmeticSource::H)),
            0x4D => Some(Instructions::BIT(1, ArithmeticSource::L)),
            0x4E => Some(Instructions::BIT(1, ArithmeticSource::HLAddr)),
            0x4F => Some(Instructions::BIT(1, ArithmeticSource::A)),
            0x50 => Some(Instructions::BIT(2, ArithmeticSource::B)),
            0x51 => Some(Instructions::BIT(2, ArithmeticSource::C)),
            0x52 => Some(Instructions::BIT(2, ArithmeticSource::D)),
            0x53 => Some(Instructions::BIT(2, ArithmeticSource::E)),
            0x54 => Some(Instructions::BIT(2, ArithmeticSource::H)),
            0x55 => Some(Instructions::BIT(2, ArithmeticSource::L)),
            0x56 => Some(Instructions::BIT(2, ArithmeticSource::HLAddr)),
            0x57 => Some(Instructions::BIT(2, ArithmeticSource::A)),
            0x58 => Some(Instructions::BIT(3, ArithmeticSource::B)),
            0x59 => Some(Instructions::BIT(3, ArithmeticSource::C)),
            0x5A => Some(Instructions::BIT(3, ArithmeticSource::D)),
            0x5B => Some(Instructions::BIT(3, ArithmeticSource::E)),
            0x5C => Some(Instructions::BIT(3, ArithmeticSource::H)),
            0x5D => Some(Instructions::BIT(3, ArithmeticSource::L)),
            0x5E => Some(Instructions::BIT(3, ArithmeticSource::HLAddr)),
            0x5F => Some(Instructions::BIT(3, ArithmeticSource::A)),
            0x60 => Some(Instructions::BIT(4, ArithmeticSource::B)),
            0x61 => Some(Instructions::BIT(4, ArithmeticSource::C)),
            0x62 => Some(Instructions::BIT(4, ArithmeticSource::D)),
            0x63 => Some(Instructions::BIT(4, ArithmeticSource::E)),
            0x64 => Some(Instructions::BIT(4, ArithmeticSource::H)),
            0x65 => Some(Instructions::BIT(4, ArithmeticSource::L)),
            0x66 => Some(Instructions::BIT(4, ArithmeticSource::HLAddr)),
            0x67 => Some(Instructions::BIT(4, ArithmeticSource::A)),
            0x68 => Some(Instructions::BIT(5, ArithmeticSource::B)),
            0x69 => Some(Instructions::BIT(5, ArithmeticSource::C)),
            0x6A => Some(Instructions::BIT(5, ArithmeticSource::D)),
            0x6B => Some(Instructions::BIT(5, ArithmeticSource::E)),
            0x6C => Some(Instructions::BIT(5, ArithmeticSource::H)),
            0x6D => Some(Instructions::BIT(5, ArithmeticSource::L)),
            0x6E => Some(Instructions::BIT(5, ArithmeticSource::HLAddr)),
            0x6F => Some(Instructions::BIT(5, ArithmeticSource::A)),
            0x70 => Some(Instructions::BIT(6, ArithmeticSource::B)),
            0x71 => Some(Instructions::BIT(6, ArithmeticSource::C)),
            0x72 => Some(Instructions::BIT(6, ArithmeticSource::D)),
            0x73 => Some(Instructions::BIT(6, ArithmeticSource::E)),
            0x74 => Some(Instructions::BIT(6, ArithmeticSource::H)),
            0x75 => Some(Instructions::BIT(6, ArithmeticSource::L)),
            0x76 => Some(Instructions::BIT(6, ArithmeticSource::HLAddr)),
            0x77 => Some(Instructions::BIT(6, ArithmeticSource::A)),
            0x78 => Some(Instructions::BIT(7, ArithmeticSource::B)),
            0x79 => Some(Instructions::BIT(7, ArithmeticSource::C)),
            0x7A => Some(Instructions::BIT(7, ArithmeticSource::D)),
            0x7B => Some(Instructions::BIT(7, ArithmeticSource::E)),
            0x7C => Some(Instructions::BIT(7, ArithmeticSource::H)),
            0x7D => Some(Instructions::BIT(7, ArithmeticSource::L)),
            0x7E => Some(Instructions::BIT(7, ArithmeticSource::HLAddr)),
            0x7F => Some(Instructions::BIT(7, ArithmeticSource::A)),
            0x80 => Some(Instructions::RES(0, ArithmeticSource::B)),
            0x81 => Some(Instructions::RES(0, ArithmeticSource::C)),
            0x82 => Some(Instructions::RES(0, ArithmeticSource::D)),
            0x83 => Some(Instructions::RES(0, ArithmeticSource::E)),
            0x84 => Some(Instructions::RES(0, ArithmeticSource::H)),
            0x85 => Some(Instructions::RES(0, ArithmeticSource::L)),
            0x86 => Some(Instructions::RES(0, ArithmeticSource::HLAddr)),
            0x87 => Some(Instructions::RES(0, ArithmeticSource::A)),
            0x88 => Some(Instructions::RES(1, ArithmeticSource::B)),
            0x89 => Some(Instructions::RES(1, ArithmeticSource::C)),
            0x8A => Some(Instructions::RES(1, ArithmeticSource::D)),
            0x8B => Some(Instructions::RES(1, ArithmeticSource::E)),
            0x8C => Some(Instructions::RES(1, ArithmeticSource::H)),
            0x8D => Some(Instructions::RES(1, ArithmeticSource::L)),
            0x8E => Some(Instructions::RES(1, ArithmeticSource::HLAddr)),
            0x8F => Some(Instructions::RES(1, ArithmeticSource::A)),
            0x90 => Some(Instructions::RES(2, ArithmeticSource::B)),
            0x91 => Some(Instructions::RES(2, ArithmeticSource::C)),
            0x92 => Some(Instructions::RES(2, ArithmeticSource::D)),
            0x93 => Some(Instructions::RES(2, ArithmeticSource::E)),
            0x94 => Some(Instructions::RES(2, ArithmeticSource::H)),
            0x95 => Some(Instructions::RES(2, ArithmeticSource::L)),
            0x96 => Some(Instructions::RES(2, ArithmeticSource::HLAddr)),
            0x97 => Some(Instructions::RES(2, ArithmeticSource::A)),
            0x98 => Some(Instructions::RES(3, ArithmeticSource::B)),
            0x99 => Some(Instructions::RES(3, ArithmeticSource::C)),
            0x9A => Some(Instructions::RES(3, ArithmeticSource::D)),
            0x9B => Some(Instructions::RES(3, ArithmeticSource::E)),
            0x9C => Some(Instructions::RES(3, ArithmeticSource::H)),
            0x9D => Some(Instructions::RES(3, ArithmeticSource::L)),
            0x9E => Some(Instructions::RES(3, ArithmeticSource::HLAddr)),
            0x9F => Some(Instructions::RES(3, ArithmeticSource::A)),
            0xA0 => Some(Instructions::RES(4, ArithmeticSource::B)),
            0xA1 => Some(Instructions::RES(4, ArithmeticSource::C)),
            0xA2 => Some(Instructions::RES(4, ArithmeticSource::D)),
            0xA3 => Some(Instructions::RES(4, ArithmeticSource::E)),
            0xA4 => Some(Instructions::RES(4, ArithmeticSource::H)),
            0xA5 => Some(Instructions::RES(4, ArithmeticSource::L)),
            0xA6 => Some(Instructions::RES(4, ArithmeticSource::HLAddr)),
            0xA7 => Some(Instructions::RES(4, ArithmeticSource::A)),
            0xA8 => Some(Instructions::RES(5, ArithmeticSource::B)),
            0xA9 => Some(Instructions::RES(5, ArithmeticSource::C)),
            0xAA => Some(Instructions::RES(5, ArithmeticSource::D)),
            0xAB => Some(Instructions::RES(5, ArithmeticSource::E)),
            0xAC => Some(Instructions::RES(5, ArithmeticSource::H)),
            0xAD => Some(Instructions::RES(5, ArithmeticSource::L)),
            0xAE => Some(Instructions::RES(5, ArithmeticSource::HLAddr)),
            0xAF => Some(Instructions::RES(5, ArithmeticSource::A)),
            0xB0 => Some(Instructions::RES(6, ArithmeticSource::B)),
            0xB1 => Some(Instructions::RES(6, ArithmeticSource::C)),
            0xB2 => Some(Instructions::RES(6, ArithmeticSource::D)),
            0xB3 => Some(Instructions::RES(6, ArithmeticSource::E)),
            0xB4 => Some(Instructions::RES(6, ArithmeticSource::H)),
            0xB5 => Some(Instructions::RES(6, ArithmeticSource::L)),
            0xB6 => Some(Instructions::RES(6, ArithmeticSource::HLAddr)),
            0xB7 => Some(Instructions::RES(6, ArithmeticSource::A)),
            0xB8 => Some(Instructions::RES(7, ArithmeticSource::B)),
            0xB9 => Some(Instructions::RES(7, ArithmeticSource::C)),
            0xBA => Some(Instructions::RES(7, ArithmeticSource::D)),
            0xBB => Some(Instructions::RES(7, ArithmeticSource::E)),
            0xBC => Some(Instructions::RES(7, ArithmeticSource::H)),
            0xBD => Some(Instructions::RES(7, ArithmeticSource::L)),
            0xBE => Some(Instructions::RES(7, ArithmeticSource::HLAddr)),
            0xBF => Some(Instructions::RES(7, ArithmeticSource::A)),
            0xC0 => Some(Instructions::SET(0, ArithmeticSource::B)),
            0xC1 => Some(Instructions::SET(0, ArithmeticSource::C)),
            0xC2 => Some(Instructions::SET(0, ArithmeticSource::D)),
            0xC3 => Some(Instructions::SET(0, ArithmeticSource::E)),
            0xC4 => Some(Instructions::SET(0, ArithmeticSource::H)),
            0xC5 => Some(Instructions::SET(0, ArithmeticSource::L)),
            0xC6 => Some(Instructions::SET(0, ArithmeticSource::HLAddr)),
            0xC7 => Some(Instructions::SET(0, ArithmeticSource::A)),
            0xC8 => Some(Instructions::SET(1, ArithmeticSource::B)),
            0xC9 => Some(Instructions::SET(1, ArithmeticSource::C)),
            0xCA => Some(Instructions::SET(1, ArithmeticSource::D)),
            0xCB => Some(Instructions::SET(1, ArithmeticSource::E)),
            0xCC => Some(Instructions::SET(1, ArithmeticSource::H)),
            0xCD => Some(Instructions::SET(1, ArithmeticSource::L)),
            0xCE => Some(Instructions::SET(1, ArithmeticSource::HLAddr)),
            0xCF => Some(Instructions::SET(1, ArithmeticSource::A)),
            0xD0 => Some(Instructions::SET(2, ArithmeticSource::B)),
            0xD1 => Some(Instructions::SET(2, ArithmeticSource::C)),
            0xD2 => Some(Instructions::SET(2, ArithmeticSource::D)),
            0xD3 => Some(Instructions::SET(2, ArithmeticSource::E)),
            0xD4 => Some(Instructions::SET(2, ArithmeticSource::H)),
            0xD5 => Some(Instructions::SET(2, ArithmeticSource::L)),
            0xD6 => Some(Instructions::SET(2, ArithmeticSource::HLAddr)),
            0xD7 => Some(Instructions::SET(2, ArithmeticSource::A)),
            0xD8 => Some(Instructions::SET(3, ArithmeticSource::B)),
            0xD9 => Some(Instructions::SET(3, ArithmeticSource::C)),
            0xDA => Some(Instructions::SET(3, ArithmeticSource::D)),
            0xDB => Some(Instructions::SET(3, ArithmeticSource::E)),
            0xDC => Some(Instructions::SET(3, ArithmeticSource::H)),
            0xDD => Some(Instructions::SET(3, ArithmeticSource::L)),
            0xDE => Some(Instructions::SET(3, ArithmeticSource::HLAddr)),
            0xDF => Some(Instructions::SET(3, ArithmeticSource::A)),
            0xE0 => Some(Instructions::SET(4, ArithmeticSource::B)),
            0xE1 => Some(Instructions::SET(4, ArithmeticSource::C)),
            0xE2 => Some(Instructions::SET(4, ArithmeticSource::D)),
            0xE3 => Some(Instructions::SET(4, ArithmeticSource::E)),
            0xE4 => Some(Instructions::SET(4, ArithmeticSource::H)),
            0xE5 => Some(Instructions::SET(4, ArithmeticSource::L)),
            0xE6 => Some(Instructions::SET(4, ArithmeticSource::HLAddr)),
            0xE7 => Some(Instructions::SET(4, ArithmeticSource::A)),
            0xE8 => Some(Instructions::SET(5, ArithmeticSource::B)),
            0xE9 => Some(Instructions::SET(5, ArithmeticSource::C)),
            0xEA => Some(Instructions::SET(5, ArithmeticSource::D)),
            0xEB => Some(Instructions::SET(5, ArithmeticSource::E)),
            0xEC => Some(Instructions::SET(5, ArithmeticSource::H)),
            0xED => Some(Instructions::SET(5, ArithmeticSource::L)),
            0xEE => Some(Instructions::SET(5, ArithmeticSource::HLAddr)),
            0xEF => Some(Instructions::SET(5, ArithmeticSource::A)),
            0xF0 => Some(Instructions::SET(6, ArithmeticSource::B)),
            0xF1 => Some(Instructions::SET(6, ArithmeticSource::C)),
            0xF2 => Some(Instructions::SET(6, ArithmeticSource::D)),
            0xF3 => Some(Instructions::SET(6, ArithmeticSource::E)),
            0xF4 => Some(Instructions::SET(6, ArithmeticSource::H)),
            0xF5 => Some(Instructions::SET(6, ArithmeticSource::L)),
            0xF6 => Some(Instructions::SET(6, ArithmeticSource::HLAddr)),
            0xF7 => Some(Instructions::SET(6, ArithmeticSource::A)),
            0xF8 => Some(Instructions::SET(7, ArithmeticSource::B)),
            0xF9 => Some(Instructions::SET(7, ArithmeticSource::C)),
            0xFA => Some(Instructions::SET(7, ArithmeticSource::D)),
            0xFB => Some(Instructions::SET(7, ArithmeticSource::E)),
            0xFC => Some(Instructions::SET(7, ArithmeticSource::H)),
            0xFD => Some(Instructions::SET(7, ArithmeticSource::L)),
            0xFE => Some(Instructions::SET(7, ArithmeticSource::HLAddr)),
            0xFF => Some(Instructions::SET(7, ArithmeticSource::A)),
        }
    }

    #[rustfmt::skip]
    pub fn from_byte_not_prefixed(byte: u8) -> Option<Instructions> {
        match byte {
            0x00 => Some(Instructions::NOP()),
            0x01 => Some(Instructions::LD(LoadType::Word(LoadWordTarget::BC,LoadWordSource::D16,))),
            0x02 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::BC,LoadByteSource::A,))),
            0x03 => Some(Instructions::INC(IncDecTarget::BC)),
            0x04 => Some(Instructions::INC(IncDecTarget::B)),
            0x05 => Some(Instructions::DEC(IncDecTarget::B)),
            0x06 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::B,LoadByteSource::D8,))),
            0x07 => Some(Instructions::RLCA()),
            0x08 => Some(Instructions::LD(LoadType::Word(LoadWordTarget::A16,LoadWordSource::SP,))),
            0x09 => Some(Instructions::ADD16(Arithmetic16Target::BC)),
            0x10 => Some(Instructions::NOP()),
            0x0A => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::BC,))),
            0x0B => Some(Instructions::DEC(IncDecTarget::BC)),
            0x0C => Some(Instructions::INC(IncDecTarget::C)),
            0x0D => Some(Instructions::DEC(IncDecTarget::C)),
            0x0E => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::C,LoadByteSource::D8,))),
            0x0F => Some(Instructions::RRCA()),
            0x11 => Some(Instructions::LD(LoadType::Word(LoadWordTarget::DE,LoadWordSource::D16,))),
            0x12 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::DE,LoadByteSource::A,))),
            0x13 => Some(Instructions::INC(IncDecTarget::DE)),
            0x14 => Some(Instructions::INC(IncDecTarget::D)),
            0x15 => Some(Instructions::DEC(IncDecTarget::D)),
            0x16 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::D,LoadByteSource::D8,))),
            0x17 => Some(Instructions::RLA()),
            0x18 => Some(Instructions::JR(JumpTest::Always)),
            0x19 => Some(Instructions::ADD16(Arithmetic16Target::DE)),
            0x1A => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::DE,))),
            0x1B => Some(Instructions::DEC(IncDecTarget::DE)),
            0x1C => Some(Instructions::INC(IncDecTarget::E)),
            0x1D => Some(Instructions::DEC(IncDecTarget::E)),
            0x1E => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::E,LoadByteSource::D8,))),
            0x1F => Some(Instructions::RRA()),
            0x20 => Some(Instructions::JR(JumpTest::NotZero)),
            0x21 => Some(Instructions::LD(LoadType::Word(LoadWordTarget::HL,LoadWordSource::D16,))),
            0x22 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::HLI,LoadByteSource::A,))),
            0x23 => Some(Instructions::INC(IncDecTarget::HL)),
            0x24 => Some(Instructions::INC(IncDecTarget::H)),
            0x25 => Some(Instructions::DEC(IncDecTarget::H)),
            0x26 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::H,LoadByteSource::D8,))),
            0x27 => Some(Instructions::DAA()),
            0x28 => Some(Instructions::JR(JumpTest::Zero)),
            0x29 => Some(Instructions::ADD16(Arithmetic16Target::HL)),
            0x2A => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::HLI,))),
            0x2B => Some(Instructions::DEC(IncDecTarget::HL)),
            0x2C => Some(Instructions::INC(IncDecTarget::L)),
            0x2D => Some(Instructions::DEC(IncDecTarget::L)),
            0x2E => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::L,LoadByteSource::D8,))),
            0x2F => Some(Instructions::CPL()),
            0x30 => Some(Instructions::JR(JumpTest::NotCarry)),
            0x31 => Some(Instructions::LD(LoadType::Word(LoadWordTarget::SP,LoadWordSource::D16,))),
            0x32 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::HLD,LoadByteSource::A,))),
            0x33 => Some(Instructions::INC(IncDecTarget::SP)),
            0x34 => Some(Instructions::INC(IncDecTarget::HLAddr)),
            0x35 => Some(Instructions::DEC(IncDecTarget::HLAddr)),
            0x36 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::HL,LoadByteSource::D8,))),
            0x37 => Some(Instructions::SCF()),
            0x38 => Some(Instructions::JR(JumpTest::Carry)),
            0x39 => Some(Instructions::ADD16(Arithmetic16Target::SP)),
            0x3A => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::HLD,))),
            0x3B => Some(Instructions::DEC(IncDecTarget::SP)),
            0x3C => Some(Instructions::INC(IncDecTarget::A)),
            0x3D => Some(Instructions::DEC(IncDecTarget::A)),
            0x3E => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::D8,))),
            0x3F => Some(Instructions::CCF()),
            0x40 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::B,LoadByteSource::B,))),
            0x41 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::B,LoadByteSource::C,))),
            0x42 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::B,LoadByteSource::D,))),
            0x43 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::B,LoadByteSource::E,))),
            0x44 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::B,LoadByteSource::H,))),
            0x45 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::B,LoadByteSource::L,))),
            0x46 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::B,LoadByteSource::HL,))),
            0x47 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::B,LoadByteSource::A,))),
            0x48 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::C,LoadByteSource::B,))),
            0x49 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::C,LoadByteSource::C,))),
            0x4A => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::C,LoadByteSource::D,))),
            0x4B => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::C,LoadByteSource::E,))),
            0x4C => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::C,LoadByteSource::H,))),
            0x4D => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::C,LoadByteSource::L,))),
            0x4E => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::C,LoadByteSource::HL,))),
            0x4F => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::C,LoadByteSource::A,))),
            0x50 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::D,LoadByteSource::B,))),
            0x51 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::D,LoadByteSource::C,))),
            0x52 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::D,LoadByteSource::D,))),
            0x53 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::D,LoadByteSource::E,))),
            0x54 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::D,LoadByteSource::H,))),
            0x55 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::D,LoadByteSource::L,))),
            0x56 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::D,LoadByteSource::HL,))),
            0x57 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::D,LoadByteSource::A,))),
            0x58 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::E,LoadByteSource::B,))),
            0x59 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::E,LoadByteSource::C,))),
            0x5A => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::E,LoadByteSource::D,))),
            0x5B => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::E,LoadByteSource::E,))),
            0x5C => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::E,LoadByteSource::H,))),
            0x5D => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::E,LoadByteSource::L,))),
            0x5E => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::E,LoadByteSource::HL,))),
            0x5F => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::E,LoadByteSource::A,))),
            0x60 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::H,LoadByteSource::B,))),
            0x61 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::H,LoadByteSource::C,))),
            0x62 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::H,LoadByteSource::D,))),
            0x63 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::H,LoadByteSource::E,))),
            0x64 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::H,LoadByteSource::H,))),
            0x65 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::H,LoadByteSource::L,))),
            0x66 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::H,LoadByteSource::HL,))),
            0x67 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::H,LoadByteSource::A,))),
            0x68 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::L,LoadByteSource::B,))),
            0x69 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::L,LoadByteSource::C,))),
            0x6A => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::L,LoadByteSource::D,))),
            0x6B => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::L,LoadByteSource::E,))),
            0x6C => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::L,LoadByteSource::H,))),
            0x6D => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::L,LoadByteSource::L,))),
            0x6E => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::L,LoadByteSource::HL,))),
            0x6F => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::L,LoadByteSource::A,))),
            0x70 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::HL,LoadByteSource::B,))),
            0x71 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::HL,LoadByteSource::C,))),
            0x72 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::HL,LoadByteSource::D,))),
            0x73 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::HL,LoadByteSource::E,))),
            0x74 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::HL,LoadByteSource::H,))),
            0x75 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::HL,LoadByteSource::L,))),
            0x76 => Some(Instructions::HALT()),
            0x77 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::HL,LoadByteSource::A,))),
            0x78 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::B,))),
            0x79 => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::C,))),
            0x7A => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::D,))),
            0x7B => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::E,))),
            0x7C => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::H,))),
            0x7D => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::L,))),
            0x7E => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::HL,))),
            0x7F => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::A,))),
            0x80 => Some(Instructions::ADD(ArithmeticTarget::A, ArithmeticSource::B)),
            0x81 => Some(Instructions::ADD(ArithmeticTarget::A, ArithmeticSource::C)),
            0x82 => Some(Instructions::ADD(ArithmeticTarget::A, ArithmeticSource::D)),
            0x83 => Some(Instructions::ADD(ArithmeticTarget::A, ArithmeticSource::E)),
            0x84 => Some(Instructions::ADD(ArithmeticTarget::A, ArithmeticSource::H)),
            0x85 => Some(Instructions::ADD(ArithmeticTarget::A, ArithmeticSource::L)),
            0x86 => Some(Instructions::ADD(ArithmeticTarget::A,ArithmeticSource::HLAddr,)),
            0x87 => Some(Instructions::ADD(ArithmeticTarget::A, ArithmeticSource::A)),
            0x88 => Some(Instructions::ADC(ArithmeticSource::B)),
            0x89 => Some(Instructions::ADC(ArithmeticSource::C)),
            0x8A => Some(Instructions::ADC(ArithmeticSource::D)),
            0x8B => Some(Instructions::ADC(ArithmeticSource::E)),
            0x8C => Some(Instructions::ADC(ArithmeticSource::H)),
            0x8D => Some(Instructions::ADC(ArithmeticSource::L)),
            0x8E => Some(Instructions::ADC(ArithmeticSource::HLAddr)),
            0x8F => Some(Instructions::ADC(ArithmeticSource::A)),
            0x90 => Some(Instructions::SUB(ArithmeticSource::B)),
            0x91 => Some(Instructions::SUB(ArithmeticSource::C)),
            0x92 => Some(Instructions::SUB(ArithmeticSource::D)),
            0x93 => Some(Instructions::SUB(ArithmeticSource::E)),
            0x94 => Some(Instructions::SUB(ArithmeticSource::H)),
            0x95 => Some(Instructions::SUB(ArithmeticSource::L)),
            0x96 => Some(Instructions::SUB(ArithmeticSource::HLAddr)),
            0x97 => Some(Instructions::SUB(ArithmeticSource::A)),
            0x98 => Some(Instructions::SBC(ArithmeticSource::B)),
            0x99 => Some(Instructions::SBC(ArithmeticSource::C)),
            0x9A => Some(Instructions::SBC(ArithmeticSource::D)),
            0x9B => Some(Instructions::SBC(ArithmeticSource::E)),
            0x9C => Some(Instructions::SBC(ArithmeticSource::H)),
            0x9D => Some(Instructions::SBC(ArithmeticSource::L)),
            0x9E => Some(Instructions::SBC(ArithmeticSource::HLAddr)),
            0x9F => Some(Instructions::SBC(ArithmeticSource::A)),
            0xA0 => Some(Instructions::AND(ArithmeticSource::B)),
            0xA1 => Some(Instructions::AND(ArithmeticSource::C)),
            0xA2 => Some(Instructions::AND(ArithmeticSource::D)),
            0xA3 => Some(Instructions::AND(ArithmeticSource::E)),
            0xA4 => Some(Instructions::AND(ArithmeticSource::H)),
            0xA5 => Some(Instructions::AND(ArithmeticSource::L)),
            0xA6 => Some(Instructions::AND(ArithmeticSource::HLAddr)),
            0xA7 => Some(Instructions::AND(ArithmeticSource::A)),
            0xA8 => Some(Instructions::XOR(ArithmeticSource::B)),
            0xA9 => Some(Instructions::XOR(ArithmeticSource::C)),
            0xAA => Some(Instructions::XOR(ArithmeticSource::D)),
            0xAB => Some(Instructions::XOR(ArithmeticSource::E)),
            0xAC => Some(Instructions::XOR(ArithmeticSource::H)),
            0xAD => Some(Instructions::XOR(ArithmeticSource::L)),
            0xAE => Some(Instructions::XOR(ArithmeticSource::HLAddr)),
            0xAF => Some(Instructions::XOR(ArithmeticSource::A)),
            0xB0 => Some(Instructions::OR(ArithmeticSource::B)),
            0xB1 => Some(Instructions::OR(ArithmeticSource::C)),
            0xB2 => Some(Instructions::OR(ArithmeticSource::D)),
            0xB3 => Some(Instructions::OR(ArithmeticSource::E)),
            0xB4 => Some(Instructions::OR(ArithmeticSource::H)),
            0xB5 => Some(Instructions::OR(ArithmeticSource::L)),
            0xB6 => Some(Instructions::OR(ArithmeticSource::HLAddr)),
            0xB7 => Some(Instructions::OR(ArithmeticSource::A)),
            0xB8 => Some(Instructions::CP(ArithmeticSource::B)),
            0xB9 => Some(Instructions::CP(ArithmeticSource::C)),
            0xBA => Some(Instructions::CP(ArithmeticSource::D)),
            0xBB => Some(Instructions::CP(ArithmeticSource::E)),
            0xBC => Some(Instructions::CP(ArithmeticSource::H)),
            0xBD => Some(Instructions::CP(ArithmeticSource::L)),
            0xBE => Some(Instructions::CP(ArithmeticSource::HLAddr)),
            0xBF => Some(Instructions::CP(ArithmeticSource::A)),
            0xC0 => Some(Instructions::RET(JumpTest::NotZero)),
            0xC1 => Some(Instructions::POP(StackTarget::BC)),
            0xC2 => Some(Instructions::JP(JumpTest::NotZero)),
            0xC3 => Some(Instructions::JP(JumpTest::Always)),
            0xC4 => Some(Instructions::CALL(JumpTest::NotZero)),
            0xC5 => Some(Instructions::PUSH(StackTarget::BC)),
            0xC6 => Some(Instructions::ADD(ArithmeticTarget::A, ArithmeticSource::U8)),
            0xC7 => Some(Instructions::RST(RSTTargets::H00)),
            0xC8 => Some(Instructions::RET(JumpTest::Zero)),
            0xC9 => Some(Instructions::RET(JumpTest::Always)),
            0xCA => Some(Instructions::JP(JumpTest::Zero)),
            0xCC => Some(Instructions::CALL(JumpTest::Zero)),
            0xCD => Some(Instructions::CALL(JumpTest::Always)),
            0xCE => Some(Instructions::ADC(ArithmeticSource::U8)),
            0xCF => Some(Instructions::RST(RSTTargets::H08)),
            0xD0 => Some(Instructions::RET(JumpTest::NotCarry)),
            0xD1 => Some(Instructions::POP(StackTarget::DE)),
            0xD2 => Some(Instructions::JP(JumpTest::NotCarry)),
            0xD4 => Some(Instructions::CALL(JumpTest::NotCarry)),
            0xD5 => Some(Instructions::PUSH(StackTarget::DE)),
            0xD6 => Some(Instructions::SUB(ArithmeticSource::U8)),
            0xD7 => Some(Instructions::RST(RSTTargets::H10)),
            0xD8 => Some(Instructions::RET(JumpTest::Carry)),
            0xD9 => Some(Instructions::RETI()),
            0xDA => Some(Instructions::JP(JumpTest::Carry)),
            0xDC => Some(Instructions::CALL(JumpTest::Carry)),
            0xDE => Some(Instructions::SBC(ArithmeticSource::U8)),
            0xDF => Some(Instructions::RST(RSTTargets::H18)),
            0xE0 => Some(Instructions::LDH(LoadType::Other(LoadOtherTarget::A8,LoadOtherSource::A,))),
            0xE1 => Some(Instructions::POP(StackTarget::HL)),
            0xE2 => Some(Instructions::LDH(LoadType::Other(LoadOtherTarget::CAddress,LoadOtherSource::A,))),
            0xE5 => Some(Instructions::PUSH(StackTarget::HL)),
            0xE6 => Some(Instructions::AND(ArithmeticSource::U8)),
            0xE7 => Some(Instructions::RST(RSTTargets::H20)),
            0xE8 => Some(Instructions::ADD(ArithmeticTarget::SP,ArithmeticSource::I8,)),
            0xE9 => Some(Instructions::JPHL()),
            0xEA => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A16,LoadByteSource::A,))),
            0xEE => Some(Instructions::XOR(ArithmeticSource::U8)),
            0xEF => Some(Instructions::RST(RSTTargets::H28)),
            0xF0 => Some(Instructions::LDH(LoadType::Other(LoadOtherTarget::A,LoadOtherSource::A8,))),
            0xF1 => Some(Instructions::POP(StackTarget::AF)),
            0xF2 => Some(Instructions::LDH(LoadType::Other(LoadOtherTarget::A,LoadOtherSource::CAddress,))),
            0xF3 => Some(Instructions::DI()),
            0xF5 => Some(Instructions::PUSH(StackTarget::AF)),
            0xF6 => Some(Instructions::OR(ArithmeticSource::U8)),
            0xF7 => Some(Instructions::RST(RSTTargets::H30)),
            0xF8 => Some(Instructions::LD(LoadType::Word(LoadWordTarget::HL,LoadWordSource::SPr8,))),
            0xF9 => Some(Instructions::LD(LoadType::Word(LoadWordTarget::SP,LoadWordSource::HL,))),
            0xFA => Some(Instructions::LD(LoadType::Byte(LoadByteTarget::A,LoadByteSource::A16,))),
            0xFB => Some(Instructions::EI()),
            0xFE => Some(Instructions::CP(ArithmeticSource::U8)),
            0xFF => Some(Instructions::RST(RSTTargets::H38)),
            _ => None,
        }
    }
}